// examples/svelte-typerank3/src/App.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte';
  import {
    createSessionRuntime,
    createTextSource,
    createDomInputController,
    createDomStatsPanel,
    createDomCursorAdapter,
    createDomTextRenderer,
    createDomThemeController,
    type StatsSnapshot
  } from 'pitype-core';
  import { initLanguageSelector, getActiveLanguage } from './ui/languageController';
  import { createResultModal } from './ui/resultModal';
  import { initInfoModal } from './ui/infoModal';
  import { createLocaleHelpers } from './ui/localeUtils';
  import { texts } from './texts';
  import { getText, updatePageText, applyLanguage } from './language';

  let textContainerRef: HTMLElement | null = null;
  let textDisplayRef: HTMLElement | null = null;
  let resultModalRef: HTMLElement | null = null;
  let restartButtonRef: HTMLButtonElement | null = null;
  let restartIconRef: HTMLButtonElement | null = null;
  let infoModalRef: HTMLElement | null = null;
  let infoTitleRef: HTMLElement | null = null;
  let infoContentRef: HTMLElement | null = null;
  let infoCloseBtnRef: HTMLButtonElement | null = null;

  let cursor: HTMLElement | null = null;
  let inputField: HTMLInputElement | null = null;

  const urlParams = new URLSearchParams(window.location.search);
  const forcedTextIndexParam = urlParams.get('text');
  const forcedTextIndex = forcedTextIndexParam !== null ? Number(forcedTextIndexParam) : null;
  const textLibrary = texts;

  let sessionRuntime: ReturnType<typeof createSessionRuntime> | null = null;
  let textRenderer: ReturnType<typeof createDomTextRenderer> | null = null;
  let cursorAdapter: ReturnType<typeof createDomCursorAdapter> | null = null;
  let inputController: ReturnType<typeof createDomInputController> | null = null;
  let resultModalController: ReturnType<typeof createResultModal> | null = null;
  let statsPanel: ReturnType<typeof createDomStatsPanel> | null = null;
  let localeHelpers: ReturnType<typeof createLocaleHelpers>;

  const infoData = {
    cpm: {
      title: 'CPM指标说明',
      content:
        '三个数字分别是：\nCPM (Characters Per Minute)\nTCPM（Total Characters Per Minute）\nWPM(Words Per Minute)\n\n CPM是每分钟输入的正确字符数量，只计算正确输入的字符。\n\nTCPM是每分钟输入的所有字符数量，包括正确和错误的字符。\n\nWPM是每分钟输入的单词数，计算方法为：\nWPM = CPM / 5，即每5个字符计为1个单词。\n\n中文输入时，每个汉字通常算作1个字符。'
    }
  } as const;

  const cleanupFns: Array<() => void> = [];

  function registerCleanup(fn: () => void): void {
    cleanupFns.push(fn);
  }

  function getCurrentPosition(): number {
    const session = sessionRuntime?.getSession();
    if (!session) return 0;
    return session.getState().position;
  }

  function createCursor(): void {
    if (!textDisplayRef) return;

    cursor = document.createElement('div');
    cursor.className = 'pitype-cursor cursor';
    textDisplayRef.appendChild(cursor);
    cursorAdapter?.resetAnimation();

    if (!document.getElementById('input-field')) {
      const newInputField = document.createElement('input');
      newInputField.type = 'text';
      newInputField.id = 'input-field';
      newInputField.setAttribute('autofocus', '');
      newInputField.classList.add('pitype-input');
      textDisplayRef.appendChild(newInputField);

      inputField = newInputField;
      inputController?.attachInput(inputField);
      inputField.style.pointerEvents = 'auto';
    }
  }

  function showResults(snapshot?: StatsSnapshot | null): void {
    const finalSnapshot = snapshot ?? sessionRuntime?.getLatestSnapshot();
    if (!finalSnapshot || !statsPanel) return;
    statsPanel.renderResults(finalSnapshot);
    resultModalController?.show();
  }

  function initSession(): void {
    const renderer = textRenderer;
    const runtime = sessionRuntime;
    const adapter = cursorAdapter;

    if (!renderer || !runtime || !adapter) return;

    let currentText = '';
    let selectedTextIndex: number | null = null;

    if (
      typeof forcedTextIndex === 'number' &&
      !Number.isNaN(forcedTextIndex) &&
      textLibrary[forcedTextIndex]
    ) {
      currentText = textLibrary[forcedTextIndex];
      selectedTextIndex = forcedTextIndex;
    } else {
      selectedTextIndex = Math.floor(Math.random() * textLibrary.length);
      currentText = textLibrary[selectedTextIndex];
    }

    const currentSource = createTextSource(currentText, {
      id: selectedTextIndex !== null ? `text-${selectedTextIndex}` : undefined,
      locale: getActiveLanguage()
    });

    runtime.dispose();
    renderer.render(currentSource);

    if (cursor) {
      cursor.remove();
      cursor = null;
    }
    adapter.resetAnimation();

    const existingInput = document.getElementById('input-field');
    if (existingInput) {
      inputController?.detachInput();
      existingInput.remove();
      inputField = null;
    }

    runtime.startSession(currentSource);

    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          adapter.cacheCharSpans();

          if ((renderer.getSpans().length ?? 0) === 0) {
            console.error('未找到任何字符元素，无法创建光标');
            return;
          }

          createCursor();

          if (!inputField) {
            console.error('输入框创建失败');
            return;
          }

          adapter.updatePosition({ immediate: true });
          adapter.enableMobileSupport();
          adapter.enableResponsiveSync();

          inputField.value = '';
          inputField.focus();
        });
      });
    });

    if (resultModalRef) {
      resultModalRef.style.display = 'none';
    }
  }

  onMount(() => {
    if (!textDisplayRef || !textContainerRef || !resultModalRef) {
      console.error('初始化失败，必要的 DOM 元素缺失');
      return;
    }

    localeHelpers = createLocaleHelpers({
      getText,
      updatePageText,
      applyLanguage
    });

    statsPanel = createDomStatsPanel({
      getLocaleText: localeHelpers.getText,
      realtime: {
        cpm: document.getElementById('cpm'),
        totalCpm: document.getElementById('total-cpm'),
        wpm: document.getElementById('wpm'),
        accuracy: document.getElementById('accuracy'),
        time: document.getElementById('time'),
        chars: document.getElementById('char-count')
      },
      result: {
        time: document.getElementById('final-time'),
        cpm: document.getElementById('final-cpm'),
        totalCpm: document.getElementById('final-total-cpm'),
        wpm: document.getElementById('final-wpm'),
        accuracy: document.getElementById('final-accuracy'),
        chars: document.getElementById('final-char-count')
      }
    });

    textRenderer = createDomTextRenderer(textDisplayRef);
    const themeController = createDomThemeController();

    cursorAdapter = createDomCursorAdapter({
      textDisplay: textDisplayRef,
      textContainer: textContainerRef,
      getCurrentPosition,
      getCursor: () => cursor,
      getInput: () => inputField,
      getSpans: () => textRenderer?.getSpans() ?? [],
      setSpans: (spans) => {
        if (textRenderer) {
          textRenderer.setSpans(spans);
        }
      }
    });

    sessionRuntime = createSessionRuntime({
      onEvaluate: (event) => {
        textRenderer?.applySpanState(event.index, event.correct);
        cursorAdapter?.scheduleRefresh();
      },
      onUndo: (event) => {
        textRenderer?.resetSpanState(event.index);
        cursorAdapter?.scheduleRefresh();
      },
      onComplete: (snapshot) => {
        if (cursor) {
          cursor.remove();
          cursor = null;
        }
        cursorAdapter?.resetAnimation();
        showResults(snapshot);
      },
      onReset: () => {
        cursorAdapter?.resetAnimation();
      },
      onSnapshot: (snapshot: StatsSnapshot | null) => {
        if (!snapshot) {
          statsPanel?.reset();
          return;
        }
        statsPanel?.renderSnapshot(snapshot);
      }
    });

    inputController = createDomInputController({
      getTypingSession: () => sessionRuntime?.getSession() ?? null,
      isResultModalVisible: () => resultModalRef?.style.display === 'flex',
      onCompositionEnd: () => cursorAdapter?.updatePosition()
    });

    resultModalController = createResultModal({
      modal: resultModalRef,
      restartButton: restartButtonRef,
      onRestart: () => initSession()
    });

    textDisplayRef.addEventListener('click', handleTextDisplayClick);
    registerCleanup(() => textDisplayRef?.removeEventListener('click', handleTextDisplayClick));

    if (restartIconRef) {
      restartIconRef.addEventListener('click', handleRestartIconClick);
      registerCleanup(() => restartIconRef?.removeEventListener('click', handleRestartIconClick));
    }

    const infoElements = document.querySelectorAll('[data-info]');
    initInfoModal({
      triggers: infoElements,
      modal: infoModalRef,
      titleElement: infoTitleRef,
      contentElement: infoContentRef,
      closeButton: infoCloseBtnRef,
      infoMap: infoData
    });

    localeHelpers.refreshLocaleText();

    initLanguageSelector({
      applyLanguage: localeHelpers.applyLanguage,
      updatePageText: localeHelpers.refreshLocaleText
    });

    const disposeTheme = themeController.init();
    registerCleanup(() => {
      disposeTheme?.();
    });

    const handleWindowLoad = (): void => {
      if ((textRenderer?.getSpans().length ?? 0) > 0 && cursor && inputField) {
        cursorAdapter?.updatePosition({ immediate: true });
        inputField.focus();
      } else {
        requestAnimationFrame(() => {
          if ((textRenderer?.getSpans().length ?? 0) === 0) {
            cursorAdapter?.cacheCharSpans();
          }
          if (cursor && inputField) {
            cursorAdapter?.updatePosition({ immediate: true });
            inputField.focus();
          }
        });
      }
    };

    window.addEventListener('load', handleWindowLoad);
    registerCleanup(() => window.removeEventListener('load', handleWindowLoad));

    initSession();
  });

  function handleTextDisplayClick(): void {
    inputController?.focusInput();
  }

  function handleRestartIconClick(): void {
    resultModalController?.hide();
    initSession();
  }

  onDestroy(() => {
    cleanupFns.forEach((fn) => fn());
    sessionRuntime?.dispose();
    cursorAdapter?.resetAnimation();
    const existingInput = document.getElementById('input-field');
    existingInput?.remove();
    cursor?.remove();
  });
</script>

<div class="pitype-container container">
  <div class="pitype-header header">
    <h1>TypeFree <span class="pitype-version version">v0.1.21-svelte</span></h1>
    <div class="pitype-controls controls">
      <div class="pitype-selector-container selector-container">
        <div class="pitype-language-selector language-selector">
          <div
            class="pitype-language-option language-option pitype-lang-zh-CN lang-zh-CN active"
            data-lang="zh-CN"
            title="简体中文"
          >CN</div>
          <div
            class="pitype-language-option language-option pitype-lang-zh-TW lang-zh-TW"
            data-lang="zh-TW"
            title="繁體中文"
          >TW</div>
          <div
            class="pitype-language-option language-option pitype-lang-en-US lang-en-US"
            data-lang="en-US"
            title="English"
          >EN</div>
        </div>
        <div class="pitype-selector-divider selector-divider"></div>
        <div class="pitype-theme-selector theme-selector">
          <div
            class="pitype-theme-option pitype-theme-dracula theme-option theme-dracula active"
            data-theme="dracula"
            title="Dracula 主题"
          ></div>
          <div
            class="pitype-theme-option pitype-theme-serika theme-option theme-serika"
            data-theme="serika"
            title="Serika 主题"
          ></div>
          <div
            class="pitype-theme-option pitype-theme-botanical theme-option theme-botanical"
            data-theme="botanical"
            title="Botanical 主题"
          ></div>
          <div
            class="pitype-theme-option pitype-theme-aether theme-option theme-aether"
            data-theme="aether"
            title="Aether 主题"
          ></div>
          <div
            class="pitype-theme-option pitype-theme-nord theme-option theme-nord"
            data-theme="nord"
            title="Nord 主题"
          ></div>
        </div>
        <button id="restart-icon" title="重新开始" bind:this={restartIconRef}>
          <i class="fas fa-redo"></i>
        </button>
      </div>
    </div>
  </div>

  <div class="pitype-stats stats">
    <div class="pitype-cpm-container cpm-container">
      <span class="pitype-cpm-label cpm-label">
        <span class="pitype-info-text info-text" data-info="cpm" title="点击查看CPM/WPM指标说明">CPM:</span>
      </span>
      <div class="pitype-cpm-values cpm-values">
        <span id="cpm" class="pitype-cpm-value cpm-value">0</span>
        <span id="total-cpm" class="pitype-tcpm-value tcpm-value">0</span>
        <span id="wpm" class="pitype-wpm-value wpm-value">0</span>
      </div>
    </div>
    <div class="pitype-stat-item stat-item">
      正确率: <span id="accuracy" class="pitype-stat-value stat-value">100%</span>
    </div>
    <div class="pitype-stat-item stat-item">
      时间: <span id="time" class="pitype-stat-value stat-value">0000.0秒</span>
    </div>
    <div class="pitype-stat-item stat-item">
      字符数: <span id="char-count" class="pitype-stat-value stat-value">0</span>
    </div>
  </div>

  <div class="pitype-text-container" bind:this={textContainerRef}>
    <div id="text-display" class="pitype-text-display" bind:this={textDisplayRef}></div>
  </div>

  <div class="pitype-footer footer">
    <span class="copyright">&copy; 2025 TypeFree - 自由无感提升输入效率</span>
  </div>
</div>

<div
  id="result-modal"
  class="pitype-modal modal"
  bind:this={resultModalRef}
  style="display: none;"
>
  <div class="pitype-modal-content modal-content">
    <h2><i class="fas fa-trophy"></i> 练习完成！</h2>
    <div class="pitype-result-stats result-stats">
      <p><span class="pitype-stat-label stat-label"><i class="fas fa-clock"></i> 总用时:</span> <span id="final-time"></span></p>
      <p><span class="pitype-stat-label stat-label"><i class="fas fa-keyboard"></i> CPM:</span> <span id="final-cpm"></span></p>
      <p><span class="pitype-stat-label stat-label"><i class="fas fa-tachometer-alt"></i> 总CPM:</span> <span id="final-total-cpm"></span></p>
      <p><span class="pitype-stat-label stat-label"><i class="fas fa-file-word"></i> WPM:</span> <span id="final-wpm"></span></p>
      <p><span class="pitype-stat-label stat-label"><i class="fas fa-check-circle"></i> 正确率:</span> <span id="final-accuracy"></span></p>
      <p><span class="pitype-stat-label stat-label"><i class="fas fa-font"></i> 总字符数:</span> <span id="final-char-count"></span></p>
    </div>
    <button id="restart-btn" bind:this={restartButtonRef}>
      <i class="fas fa-redo"></i> 重新开始
    </button>
  </div>
</div>

<div
  id="info-modal"
  class="pitype-modal modal"
  bind:this={infoModalRef}
  style="display: none;"
>
  <div class="pitype-modal-content modal-content">
    <h3 id="info-title" bind:this={infoTitleRef}>指标说明</h3>
    <p id="info-content" bind:this={infoContentRef}></p>
    <button id="info-close-btn" bind:this={infoCloseBtnRef}>关闭</button>
  </div>
</div>

// examples/vue3-typerank3/src/App.vue
<template>
  <div class="app">
    <header class="header">
      <h1>TypeFree <span class="version">Vue3</span></h1>
      <div class="controls">
        <div class="selector-container">
          <div class="language-selector">
            <button
              v-for="lang in languages"
              :key="lang"
              class="language-option"
              :class="{ active: activeLanguage === lang }"
              @click="switchLanguage(lang)"
            >
              {{ lang }}
            </button>
          </div>
          <div class="selector-divider" />
          <div class="theme-selector">
            <button
              v-for="theme in themes"
              :key="theme"
              class="theme-option"
              :data-theme="theme"
              :class="{ active: activeTheme === theme }"
              @click="switchTheme(theme)"
            />
          </div>
        </div>
        <button id="restart-btn" @click="restartSession">
          <i class="fas fa-redo" /> 重新开始
        </button>
      </div>
    </header>

    <section class="stats">
      <div class="cpm-container">
        <span class="cpm-label">
          <span class="info-text" data-info="cpm">CPM:</span>
        </span>
        <div class="cpm-values">
          <span class="cpm-value">{{ statsSnapshot.correctCpm }}</span>
          <span class="tcpm-value">{{ statsSnapshot.totalCpm }}</span>
          <span class="wpm-value">{{ statsSnapshot.wpm }}</span>
        </div>
      </div>
      <div class="stat-item">
        正确率: <span class="stat-value">{{ statsSnapshot.accuracy }}%</span>
      </div>
      <div class="stat-item">
        时间: <span class="stat-value">{{ formatDuration(statsSnapshot.durationMs) }}</span>
      </div>
      <div class="stat-item">
        字符数: <span class="stat-value">{{ statsSnapshot.totalChars }}</span>
      </div>
    </section>

    <section class="text-container" @click="focusInput">
      <div id="text-display" ref="textDisplayRef" class="text-display">
        <input
          ref="hiddenInputRef"
          id="input-field"
          type="text"
          autocomplete="off"
          @input="onInput"
          @keydown="onKeydown"
        />
        <div ref="cursorRef" class="cursor" />
      </div>
    </section>

    <div v-if="showResult" class="modal">
      <div class="modal-content">
        <h2><i class="fas fa-trophy" /> 练习完成！</h2>
        <div class="result-stats">
          <p><span class="stat-label">总用时:</span> {{ formatDuration(statsSnapshot.durationMs) }}</p>
          <p><span class="stat-label">CPM:</span> {{ statsSnapshot.correctCpm }}</p>
          <p><span class="stat-label">总CPM:</span> {{ statsSnapshot.totalCpm }}</p>
          <p><span class="stat-label">WPM:</span> {{ statsSnapshot.wpm }}</p>
          <p><span class="stat-label">正确率:</span> {{ statsSnapshot.accuracy }}%</p>
          <p><span class="stat-label">总字符数:</span> {{ statsSnapshot.totalChars }}</p>
        </div>
        <button class="modal-button" @click="closeResult">继续练习</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';
import {
  createSessionRuntime,
  createTextSource,
  createDomCursorAdapter,
  createDomInputController,
  createDomTextRenderer,
  type StatsSnapshot
} from '@pitype/core';
import { texts } from './texts';

const textDisplayRef = ref<HTMLElement | null>(null);
const cursorRef = ref<HTMLElement | null>(null);
const hiddenInputRef = ref<HTMLInputElement | null>(null);

const themes = ['dracula', 'serika', 'botanical', 'aether', 'nord'];
const languages = ['zh-CN', 'zh-TW', 'en-US'];
const activeLanguage = ref('zh-CN');
const activeTheme = ref('dracula');

const statsSnapshot = ref<StatsSnapshot>({
  startedAt: undefined,
  durationMs: 0,
  correctChars: 0,
  totalChars: 0,
  accuracy: 100,
  correctCpm: 0,
  totalCpm: 0,
  wpm: 0,
  completed: false
});

const showResult = ref(false);
const textIndex = ref(0);

const sessionRuntime = createSessionRuntime({
  onEvaluate: handleEvaluate,
  onUndo: handleUndo,
  onSnapshot: (snapshot) => {
    if (snapshot) statsSnapshot.value = snapshot;
  },
  onComplete: (snapshot) => {
    statsSnapshot.value = snapshot;
    showResult.value = true;
  },
  onReset: () => {
    showResult.value = false;
  }
});

const textRenderer = ref<ReturnType<typeof createDomTextRenderer>>();
const cursorAdapter = ref<ReturnType<typeof createDomCursorAdapter>>();
const inputController = ref<ReturnType<typeof createDomInputController>>();
const currentSource = ref(createTextSource(texts[textIndex.value], { id: 'initial' }));

function handleEvaluate(event: { index: number; correct: boolean }) {
  cursorAdapter.value?.scheduleRefresh();
}

function handleUndo() {
  cursorAdapter.value?.scheduleRefresh();
}

function formatDuration(durationMs: number) {
  return `${(durationMs / 1000).toFixed(1)} 秒`;
}

function focusInput() {
  hiddenInputRef.value?.focus();
}

function onInput(event: Event) {
  const target = event.target as HTMLInputElement;
  const value = target.value;
  target.value = '';
  if (!value) return;
  sessionRuntime.getSession()?.input(value);
}

function onKeydown(event: KeyboardEvent) {
  const session = sessionRuntime.getSession();
  if (!session) return;
  if (event.key === 'Backspace') {
    session.undo();
    event.preventDefault();
    return;
  }
  if (event.key === 'Enter') {
    session.input('\n');
    event.preventDefault();
  }
}

function restartSession() {
  textIndex.value = Math.floor(Math.random() * texts.length);
  startSession();
}

function closeResult() {
  showResult.value = false;
  restartSession();
}

function startSession() {
  const source = createTextSource(texts[textIndex.value], {
    id: `text-${textIndex.value}`,
    locale: activeLanguage.value
  });
  currentSource.value = source;
  sessionRuntime.startSession(source);
  textRenderer.value?.render(source);
  cursorAdapter.value?.cacheCharSpans();
  cursorAdapter.value?.updatePosition({ immediate: true });
  cursorAdapter.value?.enableMobileSupport();
  cursorAdapter.value?.enableResponsiveSync();
  focusInput();
}

function switchTheme(theme: string) {
  activeTheme.value = theme;
  document.body.className = '';
  if (theme !== 'dracula') {
    document.body.classList.add(`theme-${theme}`);
  }
}

function switchLanguage(lang: string) {
  activeLanguage.value = lang;
  restartSession();
}

onMounted(() => {
  if (!textDisplayRef.value || !cursorRef.value) return;
  textRenderer.value = createDomTextRenderer(textDisplayRef.value);
  cursorAdapter.value = createDomCursorAdapter({
    textDisplay: textDisplayRef.value,
    textContainer: textDisplayRef.value.parentElement,
    getCurrentPosition: () => sessionRuntime.getSession()?.getState().position ?? 0,
    getCursor: () => cursorRef.value,
    getInput: () => hiddenInputRef.value,
    getSpans: () => textRenderer.value?.getSpans() ?? [],
    setSpans: (spans) => textRenderer.value?.setSpans(spans)
  });
  inputController.value = createDomInputController({
    getTypingSession: () => sessionRuntime.getSession(),
    onCompositionEnd: () => cursorAdapter.value?.updatePosition()
  });
  if (hiddenInputRef.value) {
    inputController.value.attachInput(hiddenInputRef.value);
  }
  startSession();
});
</script>
